name: myagenda
description: Application pour voir son agenda universitaire à tout moment et facilement.
version: 4.2.2+20190521

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  http: ^0.12.0+2
  shared_preferences: ^0.5.2
  path_provider: ^1.1.0
  url_launcher: ^5.0.2
  flutter_markdown: ^0.2.0
  uuid: ^2.0.1
  html: ^0.14.0+2
  firebase_analytics: ^3.0.1
  firebase_crashlytics: ^0.0.4+3
  package_info: ^0.4.0+3
  after_layout: ^1.0.7
  flutter_calendar:
    git: git://github.com/Pyozer/flutter_calendar
  device_calendar: 0.1.2+1

  flutter_material_color_picker: ^1.0.0
  introduction_screen: ^1.0.4

  outline_material_icons: ^0.1.0
  timezone: ^0.5.4
  flutter_native_timezone: ^1.0.4
  qr_flutter: ^2.0.0+51
  
dev_dependencies:
  flutter_launcher_icons: ^0.7.0

flutter:
  uses-material-design: true

  assets:
    - res/images/
    - res/locales/
    - packages/timezone/data/2019a_all.tzf

  fonts:
     - family: GoogleSans
       fonts:
          - asset: res/fonts/GoogleSans-Regular.ttf
            style: normal
            weight: 500

          - asset: res/fonts/GoogleSans-Medium.ttf
            style: normal
            weight: 600

          - asset: res/fonts/GoogleSans-Bold.ttf
            style: normal
            weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "res/images/icon_square.png"
  image_path_android: "res/images/icon_circle.png"
  image_path_ios: "res/images/icon_ios.png"
  adaptive_icon_background: "#FFFF0000"
  adaptive_icon_foreground: "res/images/icon_foreground.png"
