name: myagenda
description: Application pour voir simplement son agenda universitaire.
version: 4.0.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.11.3+17
  shared_preferences: ^0.4.3
  path_provider: ^0.4.1
  url_launcher: ^4.0.1
  flutter_markdown: ^0.2.0
  uuid: ^1.0.3
  html: ^0.13.3+3
  firebase_analytics: ^1.0.4
  firebase_admob: ^0.6.1+1

  flutter_material_color_picker: ^0.0.4
  introduction_screen: ^0.0.4

  outline_material_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.6.1

flutter:
  uses-material-design: true

  assets:
    - res/images/icon_circle.png
    - res/images/jeancharles-mousse.jpg
    - res/images/justin-martin.jpg

    - res/images/intro_login.png
    - res/images/intro_event.png
    - res/images/intro_group.png
    - res/images/intro_internet.png
    - res/images/intro_note.png
    - res/images/intro_theme.png

    - res/images/GitHub-Mark.png
    - res/images/GitHub-Mark-Light.png

    - res/images/Twitter_Logo_Blue.png
    - res/images/Twitter_Logo_White.png

    - res/images/appstore.png
    - res/images/playstore.png

    - res/images/sad_icon.png

    - res/locales/en.json
    - res/locales/fr.json

  fonts:
     - family: GoogleSans
       fonts:
          - asset: res/fonts/GoogleSans-Regular.ttf
            style: normal
            weight: 500

          - asset: res/fonts/GoogleSans-Medium.ttf
            style: normal
            weight: 600

          - asset: res/fonts/GoogleSans-Bold.ttf
            style: normal
            weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "res/images/icon_square.png"
  image_path_android: "res/images/icon_circle.png"
  image_path_ios: "res/images/icon_ios.png"
  adaptive_icon_background: "#FFFF0000"
  adaptive_icon_foreground: "res/images/icon_foreground.png"
