name: myagenda
description: Application pour voir son agenda universitaire à tout moment et facilement.
version: 4.0.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  http: ^0.12.0+1
  shared_preferences: ^0.5.0
  path_provider: ^0.5.0
  url_launcher: ^4.2.0+1
  flutter_markdown: ^0.2.0
  uuid: ^2.0.0-rc1
  html: ^0.13.3+3
  firebase_analytics: ^1.2.0
  flutter_i18n: ^0.5.2
  package_info: ^0.4.0
  flutter_calendar:
    git: git://github.com/Pyozer/flutter_calendar.git

  flutter_material_color_picker: ^0.0.5
  introduction_screen: ^0.0.4

  outline_material_icons: ^0.1.0
  timezone: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.0

flutter:
  uses-material-design: true

  assets:
    - res/images/
    - res/locales/
    - res/2018g.tzf

  fonts:
     - family: GoogleSans
       fonts:
          - asset: res/fonts/GoogleSans-Regular.ttf
            style: normal
            weight: 500

          - asset: res/fonts/GoogleSans-Medium.ttf
            style: normal
            weight: 600

          - asset: res/fonts/GoogleSans-Bold.ttf
            style: normal
            weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "res/images/icon_square.png"
  image_path_android: "res/images/icon_circle.png"
  image_path_ios: "res/images/icon_ios.png"
  adaptive_icon_background: "#FFFF0000"
  adaptive_icon_foreground: "res/images/icon_foreground.png"
