name: myagenda
description: Application pour voir l'agenda de l'Université du Maine

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.11.3+16
  shared_preferences: ^0.4.2
  flutter_localizations:
    sdk: flutter
  material_pickers:
    git: git://github.com/long1eu/material_pickers
  introduction_screen:
      git: git://github.com/pyozer/introduction_screen

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - res/images/logo.png
    - res/locales/en.json
    - res/locales/fr.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: OpenSans
       fonts:
          - asset: res/fonts/OpenSans-Light.ttf
            style: normal
            weight: 300

          - asset: res/fonts/OpenSans-LightItalic.ttf
            style: italic
            weight: 300

          - asset: res/fonts/OpenSans-Regular.ttf
            style: normal
            weight: 400

          - asset: res/fonts/OpenSans-Italic.ttf
            style: italic
            weight: 400

          - asset: res/fonts/OpenSans-SemiBold.ttf
            style: normal
            weight: 600

          - asset: res/fonts/OpenSans-SemiBoldItalic.ttf
            style: italic
            weight: 600

          - asset: res/fonts/OpenSans-Bold.ttf
            style: normal
            weight: 700

          - asset: res/fonts/OpenSans-BoldItalic.ttf
            style: italic
            weight: 700

          - asset: res/fonts/OpenSans-ExtraBold.ttf
            style: normal
            weight: 800

          - asset: res/fonts/OpenSans-ExtraBoldItalic.ttf
            style: italic
            weight: 800
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
