name: myagenda
description: Application pour voir l'agenda de l'Université du Maine
version: 4.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.11.3+17
  shared_preferences: ^0.4.2
  url_launcher: ^3.0.3
  flutter_markdown: ^0.2.0
  uuid: ^1.0.3
  html: any
  firebase_analytics: ^1.0.3
  firebase_admob: ^0.6.1

  flutter_material_color_picker: ^0.0.4
  introduction_screen: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.6.1

flutter:
  uses-material-design: true

  assets:
    - res/images/icon_circle.png
    - res/images/jeancharles-mousse.png

    - res/images/intro_login.png
    - res/images/intro_event.png
    - res/images/intro_group.png
    - res/images/intro_internet.png
    - res/images/intro_note.png
    - res/images/intro_theme.png

    - res/images/GitHub-Mark.png
    - res/images/2x/GitHub-Mark.png
    - res/images/3x/GitHub-Mark.png

    - res/images/GitHub-Mark-Light.png
    - res/images/2x/GitHub-Mark-Light.png
    - res/images/3x/GitHub-Mark-Light.png

    - res/images/Twitter_Logo_Blue.png
    - res/images/Twitter_Logo_White.png

    - res/images/sad_icon.png

    - res/locales/en.json
    - res/locales/fr.json

  fonts:
     - family: OpenSans
       fonts:
          - asset: res/fonts/OpenSans-Light.ttf
            style: normal
            weight: 300

          - asset: res/fonts/OpenSans-LightItalic.ttf
            style: italic
            weight: 300

          - asset: res/fonts/OpenSans-Regular.ttf
            style: normal
            weight: 400

          - asset: res/fonts/OpenSans-Italic.ttf
            style: italic
            weight: 400

          - asset: res/fonts/OpenSans-SemiBold.ttf
            style: normal
            weight: 600

          - asset: res/fonts/OpenSans-SemiBoldItalic.ttf
            style: italic
            weight: 600

          - asset: res/fonts/OpenSans-Bold.ttf
            style: normal
            weight: 700

          - asset: res/fonts/OpenSans-BoldItalic.ttf
            style: italic
            weight: 700

          - asset: res/fonts/OpenSans-ExtraBold.ttf
            style: normal
            weight: 800

          - asset: res/fonts/OpenSans-ExtraBoldItalic.ttf
            style: italic
            weight: 800

flutter_icons:
  android: true
  ios: true
  image_path: "res/images/icon_circle.png"
  image_path_ios: "res/images/icon_square.png"
  adaptive_icon_background: "#FFFF0000"
  adaptive_icon_foreground: "res/images/icon_foreground.png"
