name: myagenda
description: Application pour voir l'agenda de l'Université du Maine

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.11.3+16
  shared_preferences: ^0.4.2
  flutter_localizations:
    sdk: flutter
  material_pickers:
    git: git://github.com/long1eu/material_pickers
  introduction_screen:
      git: git://github.com/pyozer/introduction_screen

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - res/images/logo.png
    - res/images/GitHub-Mark.png
    - res/images/GitHub-Mark-Light.png
    - res/images/2x/GitHub-Mark.png
    - res/images/2x/GitHub-Mark-Light.png
    - res/images/3x/GitHub-Mark.png
    - res/images/3x/GitHub-Mark-Light.png
    - res/images/Twitter_Logo_Blue.png
    - res/images/Twitter_Logo_White.png
    - res/images/jeancharles-mousse.png
    - res/locales/en.json
    - res/locales/fr.json

  fonts:
     - family: OpenSans
       fonts:
          - asset: res/fonts/OpenSans-Light.ttf
            style: normal
            weight: 300

          - asset: res/fonts/OpenSans-LightItalic.ttf
            style: italic
            weight: 300

          - asset: res/fonts/OpenSans-Regular.ttf
            style: normal
            weight: 400

          - asset: res/fonts/OpenSans-Italic.ttf
            style: italic
            weight: 400

          - asset: res/fonts/OpenSans-SemiBold.ttf
            style: normal
            weight: 600

          - asset: res/fonts/OpenSans-SemiBoldItalic.ttf
            style: italic
            weight: 600

          - asset: res/fonts/OpenSans-Bold.ttf
            style: normal
            weight: 700

          - asset: res/fonts/OpenSans-BoldItalic.ttf
            style: italic
            weight: 700

          - asset: res/fonts/OpenSans-ExtraBold.ttf
            style: normal
            weight: 800

          - asset: res/fonts/OpenSans-ExtraBoldItalic.ttf
            style: italic
            weight: 800
